[package]
name = "hocg-fan-web-client"
edition = "2021"
version.workspace = true

[dependencies]
hocg-fan-sim = { workspace = true }

dioxus = { version = "0.5", features = ["web", "router"] }

# Debug
dioxus-logger = "0.5.1"
