[package]
name = "hocg-fan-sim-derive"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.34"
proc_macro_roids = "0.7.0"
quote = "1.0.10"
syn = { version = "1.0.82", features = ["extra-traits", "visit"] }

[dev-dependencies]
pretty_assertions = "1.0.0"
